#%RAML 1.0 NamedExample
value:
  message: Hi anjali, your tickets are booked now!!
  carBookingDetails:
    partner: uber
    source: bhugaon
    destination: vimannagar
    firstname: anjali
    lastname: chavan
    NoOfSeats: 4
    price: 100
    scheduledDate: 2021-10-21
    scheduledTime: 04:30:00        
  
